name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
        node-version: ${{ matrix.node-version }}
     - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.7.0
       with:
        mongodb-version: ${{ matrix.mongodb-version }}
       with:
         command: npm run test:integration
         browser: chrome